// Q. -> why js is proto type language ;
//prototype based class

var car = {
    make: 'Toyota',
    model: 'Corolla',
    drive: function() {
      console.log('Driving...');
    },
    stop: function() {
      console.log('Stopped.');
    }
  };
  
  var myCar = Object.create(car);
  myCar.color = 'blue';
  myCar.year = 2024;
  console.log(myCar);
  console.log(myCar.drive());
  console.log(myCar.stop());
  
  // different 

  // traditional based class 
  class Car {
    constructor(make, model) {
      this.make = make;
      this.model = model;
    }
  
    drive() {
      console.log('Driving... real');
    }
  
    stop() {
      console.log('Stopped. real');
    }
  }
  
  const myCar1 = new Car('Toyota', 'Corolla');
  console.log(myCar1);
  console.log(myCar1.drive());
  console.log(myCar1.stop());


  //Q. what is event loop and its working ?

  // The event loop is a mechanism that enables JavaScript to handle asynchronous events. It is the core of JavaScript's non-blocking I/O model, which means that JavaScript can handle multiple operations at the same time without blocking the execution of other operations.

  // Sure, let's break down the functionality of the event loop in JavaScript along with a simple diagram.

  // ### Event Loop in JavaScript:

  // The event loop is a core mechanism in JavaScript's runtime environment that manages asynchronous operations and executes tasks in a non-blocking manner. It continuously checks the call stack and the task queue, ensuring that tasks are executed efficiently.

  // Here's how it works:

  // 1. **Call Stack:**
  //    - The call stack is a data structure that tracks the execution of function calls in JavaScript.
  //    - When a function is invoked, a frame representing that function call is added to the top of the call stack.
  //    - JavaScript is single-threaded, meaning it can only execute one task at a time. The call stack helps maintain the execution order of tasks.

  // 2. **Task Queue:**
  //    - The task queue is a queue data structure that holds tasks to be executed asynchronously.
  //    - Tasks in the task queue are typically generated by asynchronous operations such as timers, I/O operations, or event handlers.

  // 3. **Event Loop:**
  //    - The event loop continuously checks two main components: the call stack and the task queue.
  //    - If the call stack is empty and there are tasks in the task queue, the event loop takes a task from the task queue and pushes it onto the call stack for execution.
  //    - This mechanism ensures that asynchronous tasks are executed only when the call stack is empty, preventing blocking and allowing the JavaScript engine to handle multiple concurrent operations efficiently.

  // ### Diagram:

  // ```
  //     ┌──────────────┐           ┌──────────────┐
  //     │              │           │              │
  //     │   Call Stack │           │  Task Queue  │
  //     │              │           │              │
  //     └─────▲────────┘           └─────▲────────┘
  //           │                          │
  //   Push/Pop│                          │
  //           │                          │
  //     ┌─────┴────────┐           ┌─────┴────────┐
  //     │              │           │              │
  //     │   Execution  │           │  Asynchronous│web/api
  //     │              │           │   Operations │
  //     └──────────────┘           └──────────────┘
  // ```

  // - The `Call Stack` represents the stack of function calls being executed.
  // - The `Task Queue` holds asynchronous tasks waiting to be executed.
  // - As tasks are completed or functions return, they are popped off the call stack.
  // - When the call stack is empty, the event loop checks if there are tasks in the task queue.
  // - If there are tasks in the task queue, the event loop takes a task and pushes it onto the call stack for execution.

  // This cycle continues, allowing JavaScript to handle asynchronous operations effectively without blocking the main execution thread.
  


  
  // Yes, the event loop is a fundamental mechanism in JavaScript that governs the execution of all code, regardless of where it's written within a JavaScript application. Whether the code is written in the main script file, inside functions, or within asynchronous operations, the event loop manages the order of execution.

  // Here's how the event loop works with different pieces of JavaScript code:
  
  // 1. **Synchronous Code**: When you write synchronous code in JavaScript, such as variable declarations, function calls, or loops, the event loop processes this code sequentially. Each line of code is executed one after the other, and the event loop ensures that the next piece of code is executed only after the current one has finished executing.
  
  //    ```javascript
  //    // Synchronous code example
  //    console.log("Hello"); // Executed first
  //    alert("World"); // Executed second after the alert is dismissed
  //    ```
  
  // 2. **Asynchronous Code**: When you write asynchronous code, such as using setTimeout, setInterval, AJAX requests, or event listeners, the event loop handles the scheduling and execution of these operations. The callback functions associated with asynchronous operations are queued up and executed when the event loop reaches them, after the current synchronous code has finished executing.
  
  //    ```javascript
  //    // Asynchronous code example
  //    console.log("Start");
  //    setTimeout(() => {
  //        console.log("Delayed log");
  //    }, 1000);
  //    console.log("End");
  //    ```
  
  //    In this example, "Start" and "End" will be logged immediately, while "Delayed log" will be logged after approximately one second, as it's scheduled to run asynchronously using setTimeout.
  
  // 3. **Promises and async/await**: Even with Promises and async/await syntax, which are used for handling asynchronous operations in a more structured and readable way, the event loop still plays a crucial role. Promise handlers and async functions are scheduled in the microtask queue, which is processed before the regular task queue (where setTimeout and other asynchronous tasks reside). This ensures that Promise handlers and async functions are executed as soon as possible after the current synchronous code block completes.
  
  // In summary, the event loop is responsible for managing the execution order of all pieces of JavaScript code, whether synchronous or asynchronous, ensuring that JavaScript remains single-threaded and non-blocking.